In [2]:
import numpy as np
import cv2 as cv

In [3]:
path1 = "calibration/calibration_params2"

Q = np.load(path1 + "/Q.npy")
E = np.load(path1 + "/E.npy")
F = np.load(path1 + "/F.npy")
R = np.load(path1 + "/R.npy")
T = np.load(path1 + "/T.npy")

In [5]:
print(T)

[[-2.03023022e+01]
 [ 7.63880020e-03]
 [-2.27821902e+00]]


In [4]:
print(Q)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -1.53151461e+02]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -2.43174231e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.68744797e+03]
 [ 0.00000000e+00  0.00000000e+00  4.89482761e-02 -0.00000000e+00]]
