In [ ]:
import numpy as np

In [7]:
# parameters1
undistortRectifyMapLx1 = np.load("../calibration_params/undistortRectifyMapLx.npy")
undistortRectifyMapLy1 = np.load("../calibration_params/undistortRectifyMapLy.npy")
undistortRectifyMapRx1 = np.load("../calibration_params/undistortRectifyMapRx.npy")
undistortRectifyMapRy1 = np.load("../calibration_params/undistortRectifyMapRy.npy")
Q1 = np.load("../calibration_params/Q.npy")

In [8]:
# parameters 2
undistortRectifyMapLx2 = np.load("../calibration_params2/undistortRectifyMapLx.npy")
undistortRectifyMapLy2 = np.load("../calibration_params2/undistortRectifyMapLy.npy")
undistortRectifyMapRx2 = np.load("../calibration_params2/undistortRectifyMapRx.npy")
undistortRectifyMapRy2 = np.load("../calibration_params2/undistortRectifyMapRy.npy")
Q2 = np.load("../calibration_params2/Q.npy")

In [10]:
# compare 
print(undistortRectifyMapLx1)
print()
print(undistortRectifyMapLx2)

[[ 17.051645  17.958778  18.866354 ... 631.4      632.3484   633.2964  ]
 [ 17.01811   17.925367  18.833065 ... 631.42395  632.3725   633.3207  ]
 [ 16.984722  17.892101  18.799921 ... 631.4478   632.3965   633.3448  ]
 ...
 [ 13.852317  14.761869  15.671844 ... 629.172    630.12396  631.07556 ]
 [ 13.8718    14.78125   15.69112  ... 629.13995  630.0918   631.0433  ]
 [ 13.891414  14.800759  15.710526 ... 629.1078   630.05945  631.01086 ]]

[[  8.197422    9.1549225  10.112639  ... 619.39124   620.2932
  621.1948   ]
 [  8.170583    9.128169   10.085972  ... 619.41364   620.3157
  621.21735  ]
 [  8.143852    9.101525   10.059413  ... 619.436     620.3381
  621.2398   ]
 ...
 [  7.972156    8.93233     9.892726  ... 620.91125   621.81555
  622.7195   ]
 [  7.9983664   8.958463    9.91878   ... 620.89496   621.7992
  622.70306  ]
 [  8.024691    8.984709    9.944948  ... 620.8786    621.7828
  622.68665  ]]


In [11]:
print(undistortRectifyMapLy1)
print()
print(undistortRectifyMapLy2)

[[  8.851509    8.819896    8.788408  ...   7.1542      7.1826944
    7.2113433]
 [  9.785445    9.754007    9.722695  ...   8.108625    8.1369915
    8.16551  ]
 [ 10.719672   10.68841    10.657272  ...   9.06337     9.091607
    9.119997 ]
 ...
 [465.45148   465.48822   465.5249    ... 474.32764   474.3162
  474.3046   ]
 [466.3927    466.42963   466.46643   ... 475.28928   475.27774
  475.26605  ]
 [467.33368   467.37076   467.40775   ... 476.25067   476.239
  476.2272   ]]

[[  3.944776    3.9321587   3.9196246 ...  10.950777   10.982852
   11.014982 ]
 [  4.907915    4.8953485   4.882865  ...  11.8833885  11.915331
   11.947327 ]
 [  5.871293    5.858777    5.846344  ...  12.816212   12.848021
   12.879883 ]
 ...
 [473.3388    473.34918   473.35947   ... 464.7493    464.71475
  464.68018  ]
 [474.30725   474.3177    474.32803   ... 465.68704   465.65237
  465.61765  ]
 [475.27548   475.28598   475.2964    ... 466.6246    466.58978
  466.55493  ]]


In [12]:
print(Q1)
print()
print(Q2)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -4.25815582e+02]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -2.41543482e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.71010551e+03]
 [ 0.00000000e+00  0.00000000e+00  4.91671720e-02 -0.00000000e+00]]

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -1.53151461e+02]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -2.43174231e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.68744797e+03]
 [ 0.00000000e+00  0.00000000e+00  4.89482761e-02 -0.00000000e+00]]
